# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5afd89bb0ca621afa74fd328c310916363a2852a9554ae28aef96e983ecb73435d2736a678809ad81fdf76b6bcec0821913c48d06db458697e5343afaf482a8

test:
  secret_key_base: 019a01a5ec5f45d20b3dc054772558f31ed58dac0df74fe470c2d51f745a5ea93bb63ca5619669c980d51d3ed8a1c6fef542091d2e2a79be180e159854fd5c8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
